#!/usr/bin/env python3
"""
Regenerate org_enums/__init__.py with explicit imports and static __all__.

It scans all .py files under org_enums/ (except __init__.py),
finds classes inheriting from enum.StrEnum, and writes
explicit imports + __all__ as a tuple literal.
"""

import ast
from pathlib import Path
from textwrap import dedent

PKG_DIR = Path(__file__).resolve().parent.parent / "org_enums"


def extract_strenum_classes(path: Path) -> list[str]:
    """Return names of classes inheriting from StrEnum in the given file."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            for base in node.bases:
                if (isinstance(base, ast.Name) and base.id == "StrEnum") or (isinstance(base, ast.Attribute) and base.attr == "StrEnum"):
                    names.append(node.name)
    return names


def main() -> None:
    imports: list[str] = []
    all_items: list[str] = []

    for pyfile in sorted(PKG_DIR.glob("*.py")):
        if pyfile.name == "__init__.py":
            continue
        class_names = extract_strenum_classes(pyfile)
        if not class_names:
            continue
        modname = pyfile.stem
        imports.append(f"from .{modname} import {', '.join(class_names)}")
        all_items.extend(class_names)

    imports_code = "\n".join(imports)
    init_code = dedent(f"""\
        \"\"\"Auto-generated by tools/gen_init.py.

        Do not edit by hand. Run `python tools/gen_init.py` after changing enums.
        \"\"\"
        from __future__ import annotations
        {imports_code}

        __all__ = ({', '.join(repr(n) for n in all_items)},)
        """)

    (PKG_DIR / "__init__.py").write_text(init_code + "\n", encoding="utf-8")
    print("Re-generated __init__.py with:", ", ".join(all_items))


if __name__ == "__main__":
    main()
